name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags (v1.0.0, etc.)

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            artifact_name: rs-wavelog-gate-macos
            asset_name: rs-wavelog-gate
          - os: windows-latest
            artifact_name: rs-wavelog-gate-windows
            asset_name: rs-wavelog-gate.exe

    steps:
      - uses: actions/checkout@v4
      
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
            name: ${{ matrix.artifact_name }}
            path: target/release/${{ matrix.asset_name }}

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4

      - name: Publish built binary to GitHub releases
        run: |
          gh release create --generate-notes ./rs-wavelog-gate-macos/rs-wavelog-gate ./rs-wavelog-gate-windows/rs-wavelog-gate.exe
        env:
          GH_TOKEN: ${{ github.token }}


      