name: Cache

on:
  push:
    branches:
      - main

jobs:
  cache:
    name: Cache
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
          - os: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Cache
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-
            ${{ runner.os }}-cargo-

      - name: Install cargo-bundle (macOS)
        if: matrix.os == 'macos-latest' && steps.cache.outputs.cache-hit != 'true'
        run: |
          if ! cargo-bundle --version >/dev/null 2>&1; then
            echo "Installing cargo-bundle..."
            cargo install cargo-bundle --force
          else
            echo "cargo-bundle already installed, skipping installation"
          fi

      - name: Install cargo-edit
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          if ! cargo set-version --version >/dev/null 2>&1; then
            echo "Installing cargo-edit..."
            cargo install cargo-edit --force
          else
            echo "cargo-edit already installed, skipping installation"
          fi  

      - name: Build
        if: steps.cache.outputs.cache-hit != 'true'
        run: cargo build --profile release