name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags (v1.0.0, etc.)

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            artifact_name: rs-wavelog-gate-macos
            asset_name: rs-wavelog-gate
            bundle_name: "WavelogGate.app"
          - os: windows-latest
            artifact_name: rs-wavelog-gate-windows
            asset_name: rs-wavelog-gate.exe

    steps:
      - uses: actions/checkout@v4
      - name: Cache Cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-
            ${{ runner.os }}-cargo-
      
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      
      - name: Install sccache
        uses: mozilla-actions/sccache-action@v0.0.5
        continue-on-error: true
        
      - name: Configure sccache
        run: |
          if command -v sccache &> /dev/null; then
            echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
            echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
            echo "sccache is available, enabling it"
          else
            echo "sccache is not available, skipping"
          fi
      
      - name: Install cargo-bundle (macOS)
        if: matrix.os == 'macos-latest'
        run: cargo install cargo-bundle

      - name: Build release binary
        run: |
          export CARGO_INCREMENTAL=1
          if cargo build --profile release 2>/dev/null || cargo build --release; then
            echo "Build successful"
          else
            echo "Build failed, trying without sccache"
            unset RUSTC_WRAPPER
            unset SCCACHE_GHA_ENABLED
            cargo build --release
          fi
        env:
          CARGO_NET_GIT_FETCH_WITH_CLI: true

      - name: Create macOS app bundle with icon
        if: matrix.os == 'macos-latest'
        run: cargo bundle --release

      - name: Upload macOS app bundle
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
            name: ${{ matrix.artifact_name }}
            path: target/release/${{ matrix.bundle_name }}

      - name: Upload Windows executable
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
            name: ${{ matrix.artifact_name }}
            path: target/release/${{ matrix.asset_name }}

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
      
      - name: Prepare macOS app bundle
        run: |
          cd rs-wavelog-gate-macos
          zip -r ../rs-wavelog-gate-macos.zip "WavelogGate.app"
          cd ..
      
      - name: Prepare Windows executable
        run: |
          cd rs-wavelog-gate-windows
          chmod +x rs-wavelog-gate.exe
          zip ../rs-wavelog-gate-windows.zip rs-wavelog-gate.exe
          cd ..
      
      - name: Publish built binaries to GitHub releases
        run: |
          gh release create ${{ github.ref_name }} \
            --generate-notes \
            rs-wavelog-gate-macos.zip#"macOS App Bundle" \
            rs-wavelog-gate-windows.zip#"Windows Executable"
        env:
          GH_TOKEN: ${{ github.token }}